### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [thomasluizzi/TeaCozy#5]
Grade: Exceeds expectations

Summary: Really nice job on this project, the site looks great. Your code is very well organized and well thought out. Take a look at the issues I created as they point out some tweaks and new techniques you can implement. Overall very good job, you are ready for the next units.

**Comment by thomasluizzi** [comment]
Thanks for the feedback.  I was struggling a bit with margins, particularly with the header and its absolute position with the main tag.  Setting its Top to 0px did the trick after some try and error.
